name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Checkout code
        uses: actions/checkout@main #consider using pin for dependabot auto update
        
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    if: ${{ github.event_name == 'push' }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.merge_commit_sha }}
            fetch-depth: '0'
            
        - name: Bump version and push tag
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          if: ${{ !contains(env.COMMIT_MESSAGES, '#SKIP') }}
          uses: anothrNick/github-tag-action@v1

  send_notification:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - name: The job has succeeded
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: |
              ✅ Workflow Success for ${{ github.repository }}!
              GitHub Actions workflow run completed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
                
      - name: The job has failed
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: |
              ❌ Workflow Failure for ${{ github.repository }}!
              GitHub Actions workflow run completed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: The job has canceled
        if: ${{ cancelled() }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: |
              ⚠️ Workflow Canceled for ${{ github.repository }}!
              GitHub Actions workflow run completed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            
