name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      - name: Say hello
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: ${{ contains(env.COMMIT_MESSAGES, '#SKIP') }}
        run: |
          echo "Hello World!"

      - name: Force step failure
        run: |
          echo "Simulating a failure!"
          exit 1

      - name: The job has succeeded
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: |
              ✅ Workflow Success for ${{ github.repository }}!
              GitHub Actions workflow run completed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
              
      - name: The job has failed
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: |
              ❌ Workflow Failure for ${{ github.repository }}!
              GitHub Actions workflow run completed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: The job has canceled
        if: ${{ cancelled() }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: |
              ⚠️ Workflow Canceled for ${{ github.repository }}!
              GitHub Actions workflow run completed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
